# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcef7ed06be8925dc60abd75de6fa8d2f4963444dc17283c91200c9135aeaba2301eec1343ed52797d8de5ef10ec8d05790598ef3b499ed57259437e7eb6ad47

test:
  secret_key_base: c5487eb330b439209d1095412fb28dc5f5ffaab5913a335857410db74c9270e59ff0fdaba08cccbe7aff1fc90c3dd996e2d201c98c44e9b558408840cbf80659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
